Repository vernemq/vernemq, pull requests merged in 2019-07, with the labels that each got.

#1233 Replace duplicate is_binary(Pass) check
  THANKS
  apps/vmq_diversity/src/vmq_diversity_bcrypt.erl
  changelog.md
Labels: bug

#1260 Upgrade cuttlefish to the latest version 2.2.0
  changelog.md
  rebar.config
  rebar.lock
Labels: cuttlefish

#1257 Fix `vmq_diversity` supervisor restart shutdown issue (#1241)
  apps/vmq_diversity/rebar.config
  apps/vmq_diversity/src/vmq_diversity_redis.erl
  changelog.md
  rebar.lock
Labels: vmq_diversity
